
#-------------------------------------------------------------------------------------
#-------------------------- PROGRAMACION ORIENTADA A OBJETOS -------------------------
#-------------------------------------------------------------------------------------

In [1]:
import numpy as np

numeros  = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(numeros[3:8])

[13 14 15 16 17]


In [12]:
#-------------------------------------------------------------------------------------
#----- MATRIZ DE CEROS ---------------------------------------------------------------

X = np.zeros([4,4])
print(X[0][1])
print(X.shape)


0.0
(4, 4)


In [20]:
#----- MATRIZ DE CEROS - VACIOS - 1'S--------------------------------------------------------------

x = np.zeros([4,6])
print(x)
x = np.ones([4,6])
print(x)
x = np.empty([4,6])
print(x)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [21]:
#----- MATRIZ RANDOM-------------------------------------------------------------

x = np.random.rand(2,3)
print(X)


[[ 1  2  3  5]
 [ 7  8  9 10]]


In [18]:
#-------------------------------------------------------------------------------------
#----- MATRIZ RECORRIDO ---------------------------------------------------------------

X = np.array([[1,2,3,5], [7,8,9,10]])
print('x= \n', X)
print(X[1:,1:3])


x= 
 [[ 1  2  3  5]
 [ 7  8  9 10]]
[[8 9]]


In [25]:
#----- EJERCICIO ---------------------------------------------------------------¨
a = np.array([ [1, 0], 
               [-1, 2], 
               [1,3] ])
b = np.array([ [-3, 3], 
               [2, 0], 
               [7, 16] ])
#x =  np.array()
print(a + b)
print(a - b)
print(a * b)
print(a / b)

#----- funciones existentes ---------------------------------------------------------------¨


print(np.add(a,b))
print(np.subtract(a,b))
#etc

[[-2  3]
 [ 1  2]
 [ 8 19]]
[[  4  -3]
 [ -3   2]
 [ -6 -13]]
[[-3  0]
 [-2  0]
 [ 7 48]]
[[-0.33333333  0.        ]
 [-0.5                inf]
 [ 0.14285714  0.1875    ]]
[[-2  3]
 [ 1  2]
 [ 8 19]]


C:\Users\DELL\AppData\Local\Temp/ipykernel_23048/424217331.py:12: RuntimeWarning: divide by zero encountered in true_divide
  print(a / b)


In [26]:
#-----------------------------------------------------------------------------------------------
#----- MULTIPLICACION DE MATRICES---------------------------------------------------------------

a = np.array([ [1, 0], 
               [-1, 2], 
               [1,3] ])
b = np.array([ [-3, 3, 5], 
               [2, 0, 7] ])
#x =  np.array()
print(a@b)

[[-3  3  5]
 [ 7 -3  9]
 [ 3  3 26]]


In [ ]:
#----- MATRICES - TRANSPIESTA ---------------------------------------------------------------¨


In [27]:
#----- MATRICES - REHSAPE ---------------------------------------------------------------¨
x = np.array([2, 3, 4, 5])
x = x.reshape(2,2)
print(x)

[[2 3]
 [4 5]]


In [28]:
#----- MATRICES - INDEXACION BOOLEANA ---------------------------------------------------------------¨
X = np.array([3,4,5,5,7,7])
mask = [ X > 4]
print(mask)

[array([False, False,  True,  True,  True,  True])]


In [7]:
#----- MATRICES - ALEATORIOS ---------------------------------------------------------------¨
X = np.array([3,4,5,5,7,7])
mask = [ X > 4]
print(mask)

[array([False, False,  True,  True,  True,  True])]


In [8]:
#----- EJERCICIOS---------------------------------------------------------------¨
#-- EJERCICIOS 1 ---------------------------------------------------------------

x = np.random.rand(1,30)
print(x)

#-- EJERCICIOS 2 ---------------------------------------------------------------
x = np.transpose(x)
print(x)

#-- EJERCICIOS 3 ---------------------------------------------------------------
x1 = np.random.rand(4, 4)
print(x1)



[[0.08178563 0.21763718 0.49819745 0.25310871 0.77072092 0.44171487
  0.61801385 0.27106092 0.55480675 0.48584474 0.38157879 0.34748024
  0.23484592 0.26171189 0.04572195 0.45587936 0.34650498 0.57135442
  0.8524391  0.30843169 0.13837061 0.12692398 0.41887031 0.70039829
  0.51954409 0.99671107 0.41674791 0.32036659 0.26940641 0.08927312]]
[[0.08178563]
 [0.21763718]
 [0.49819745]
 [0.25310871]
 [0.77072092]
 [0.44171487]
 [0.61801385]
 [0.27106092]
 [0.55480675]
 [0.48584474]
 [0.38157879]
 [0.34748024]
 [0.23484592]
 [0.26171189]
 [0.04572195]
 [0.45587936]
 [0.34650498]
 [0.57135442]
 [0.8524391 ]
 [0.30843169]
 [0.13837061]
 [0.12692398]
 [0.41887031]
 [0.70039829]
 [0.51954409]
 [0.99671107]
 [0.41674791]
 [0.32036659]
 [0.26940641]
 [0.08927312]]
[[0.02219576 0.15159859 0.65341854 0.45347582]
 [0.06472407 0.13548484 0.08828444 0.39463553]
 [0.53988807 0.68575149 0.76088504 0.97848644]
 [0.59035769 0.72761601 0.47763907 0.60358455]]
[[1.         0.82838513 0.40991359 0.94594786 0.

In [17]:

#-- EJERCICIOS 4 ---------------------------------------------------------------
'''
6,6
diagonal 1
A

6,6
diagonal 2
B
'''

A = np.random.rand(6, 6)
B = np.random.rand(6, 6)

for x in range(len(A)):
    for y in range(len(A[x])):
        if x == y:
            A[x][y]=1

print(A)

for x in range(len(B)):
    for y in range(len(B[x])):
        if x + y == len(B[x])-1:
            B[x][y]=1
#B = np.transpose(A)

print(B)


[[1.         0.08319718 0.43670186 0.28870243 0.0567126  0.66754575]
 [0.04814353 1.         0.88774962 0.6637426  0.42762492 0.8112929 ]
 [0.43050254 0.89438994 1.         0.06250028 0.62647859 0.37987811]
 [0.033798   0.47478536 0.91277604 1.         0.30765826 0.36834273]
 [0.76985559 0.5846149  0.7713546  0.60862356 1.         0.60119873]
 [0.35748124 0.67084789 0.89390905 0.35145012 0.68365422 1.        ]]
[[0.22114683 0.3077234  0.250239   0.95238864 0.06277806 1.        ]
 [0.86825788 0.72488361 0.78312206 0.80476974 1.         0.85628379]
 [0.13512515 0.17194167 0.33505587 1.         0.40021264 0.310956  ]
 [0.71921569 0.06091427 1.         0.9263774  0.4600326  0.63363191]
 [0.50572953 1.         0.92248039 0.49250188 0.58201449 0.98178343]
 [1.         0.52844163 0.1960344  0.29298557 0.02722534 0.13749295]]


In [52]:
A1 = np.random.randint(6, size=(6,6))
B1 = np.random.randint(6, size=(6,6))

mask = [A1 == B1]

print(A1, '\n')
print(B1, '\n')
print([A1 == B1], '\n')



[[5 3 5 4 4 0]
 [4 3 1 5 3 4]
 [5 1 3 3 1 4]
 [1 4 1 3 2 1]
 [0 2 2 5 1 2]
 [3 2 1 2 3 3]] 

[[0 5 4 2 3 2]
 [2 5 5 5 1 4]
 [2 1 4 2 4 3]
 [5 5 3 2 4 1]
 [5 0 0 0 5 1]
 [1 5 2 0 0 2]] 

[array([[False, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])] 



In [44]:
#-- 6
A1 = np.random.randint(6, size=(6,6))
arr_suma = []
print(A1)
'''
mask = np.array([len(A1[0]), 1])
for x in range(len(A1)):
    for y in range(len(A1[x])):
        acum = acum + A1[x][y]
    mask[0][x] = acum
    acum = 0
print(mask) 
'''
#mask = np.array([len(A1[0]), 1])
for x in range(len(A1)):
    suma = sum(A1[x]) 
    arr_suma.append(suma)
print(arr_suma)


[[3 0 4 5 1 1]
 [4 3 3 2 2 5]
 [1 0 1 0 5 0]
 [5 0 4 4 5 5]
 [4 2 0 1 5 2]
 [5 3 3 0 1 5]]
[14, 19, 7, 23, 14, 17]


In [47]:
#-- 7
acum=0
print(A1)
for x in range(len(A1)):
    for y in range(len(A1[x])):
        if x == y:
            acum= acum + A1[x][y]
print(acum)


[[3 0 4 5 1 1]
 [4 3 3 2 2 5]
 [1 0 1 0 5 0]
 [5 0 4 4 5 5]
 [4 2 0 1 5 2]
 [5 3 3 0 1 5]]
21


In [48]:
#-- 8
A2 = A1
print(A1)
for x in range(len(A1)):
    for y in range(len(A1[x])):
        if y == 0 :
             A2[x][y] = 10
print(A2)


[[3 0 4 5 1 1]
 [4 3 3 2 2 5]
 [1 0 1 0 5 0]
 [5 0 4 4 5 5]
 [4 2 0 1 5 2]
 [5 3 3 0 1 5]]
[[10  0  4  5  1  1]
 [10  3  3  2  2  5]
 [10  0  1  0  5  0]
 [10  0  4  4  5  5]
 [10  2  0  1  5  2]
 [10  3  3  0  1  5]]


In [51]:
#-- 8
A2 = np.transpose( A1 )
AR = []
print(A2)
for x in range(len(A2)):
    print(np.max(A2[x]) , ' ', np.min(A2[x]))
    #for y in range(len(A1[x])):



[[10 10 10 10 10 10]
 [ 0  3  0  0  2  3]
 [ 4  3  1  4  0  3]
 [ 5  2  0  4  1  0]
 [ 1  2  5  5  5  1]
 [ 1  5  0  5  2  5]]
10   10
3   0
4   0
5   0
5   1
5   0


**ejerciciso2**

In [66]:
#-3--Cree la función CANT_VECES(matriz)
def CANT_VECES(matriz):
    c_cantidad = []
    c_valor = []
    print('Listar cant de veces que parece:')  
    for x in range(len(matriz)):
        for y in range(len(matriz[x])):
            #if not( matriz[x][y] in c_valor):
                valor = matriz[x][y]
                cantidad = ( matriz == valor).sum()
                #if not cantidad % 2 == 0:
                c_valor.append(matriz[x][y])
                c_cantidad.append(cantidad)
                

    for z in range(len(c_valor)):
        print(c_valor[z], 'aparece ',c_cantidad[z], 'veces')

a=[[2, 2, 1, 3, 2], 
    [3, 4, 2, 2, 1], 
    [1, 3, 4, 3, 4],
    [2, 3, 2, 4, 2],
    [1, 2, 3, 4, 1]] 
CANT_VECES(a)
    


Listar cant de veces que parece:


AttributeError: 'bool' object has no attribute 'sum'

In [69]:
#--4
a=[[2, 2, 1, 3, 2], 
    [3, 4, 2, 2, 1], 
    [1, 3, 4, 3, 4],
    [2, 3, 2, 4, 2],
    [1, 2, 3, 4, 6]]
ls = np.bincount(a)
mask = np.unique(a)
print(mask)
print(ls)

[1 2 3]
[0 1 3 1]


**PANDAS**

In [1]:
import pandas as pd

df = pd.read_csv('D:/Maestria/1er Semestre/Clases/Code/Data/Churn Modeling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [2]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

*ANALISIS BASICO DE LOS DATOS*


In [ ]:
#Entender los datos antes de empezar con el analisis
#Verificar
#-- Tipos de datos
#-- Distribucion de datos
#Identificar problemas con los datos

In [4]:
##Tipos de datos
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object